name: first workflow
on:
  push:
    branches:
      - main


jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: print awelcome message
      run: echo "welcome to our first github"
      
    - name: checkout repository
      uses: actions/checkout@4.2.2
    - name: list repository files
      run: ls -a
      
